
# default
spring:
  profiles:
    active: "local"

---

spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@121.166.140.188:1521:IWSPDB
    username: infoCMS
    password: koiware123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: LogHikariCP
      max-lifetime: 200000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
           
cravis:
  uri:
    #ilogin: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ILOGIN"
    #icfcti: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ICFCTI"
    #ignotp: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/IGNOTP"
    #icfotp: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ICFOTP"
    #isnsms: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ICFOTP"
    #iec005: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/IEC005"
    #iac002: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/IAC002"
    #itf001: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ITF001"
    #itf002: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ITF002"
    #itf003: "https://cms.vietabank.com.vn/apilux-gateway-vab/v1.0/services/api/v1/ITF003"
    ilogin: "https://103.160.89.21:8443/services/api/v1/ILOGIN"
    icfcti: "https://103.160.89.21:8443/services/api/v1/ICFCTI"
    ignotp: "https://103.160.89.21:8443/services/api/v1/IGNOTP"
    icfotp: "https://103.160.89.21:8443/services/api/v1/ICFOTP"
    isnsms: "https://103.160.89.21:8443/services/api/v1/ISNSMS"
    iec005: "https://103.160.89.21:8443/services/api/v1/IEC005"
    iac002: "https://103.160.89.21:8443/services/api/v1/IAC002"
    itf001: "https://103.160.89.21:8443/services/api/v1/ITF001"
    itf002: "https://103.160.89.21:8443/services/api/v1/ITF002"
    itf003: "https://103.160.89.21:8443/services/api/v1/ITF003"
    accessKey: "INFOPLUS"
    signature: "iwIY9hx1ckg="    
    
server:
  port : 8082


template:
     path: "/home/was/info_cms/templates/"     
     
     
upload:
  path: "/home/was/info_cms/consent/"
  url:
  user:
  password:
  port:
     
---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@121.166.140.188:1521:IWSPDB
    username: infoCMS
    password: koiware123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: LogHikariCP
      max-lifetime: 200000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

cravis:
  uri:
    ilogin: "https://192.168.31.81:8443/services/api/v1/ILOGIN"
    icfcti: "https://192.168.31.81:8443/services/api/v1/ICFCTI"
    ignotp: "https://192.168.31.81:8443/services/api/v1/IGNOTP"
    icfotp: "https://192.168.31.81:8443/services/api/v1/ICFOTP"
    isnsms: "https://192.168.31.81:8443/services/api/v1/ISNSMS"
    iec005: "https://192.168.31.81:8443/services/api/v1/IEC005"
    iac002: "https://192.168.31.81:8443/services/api/v1/IAC002"
    itf001: "https://192.168.31.81:8443/services/api/v1/ITF001"
    itf002: "https://192.168.31.81:8443/services/api/v1/ITF002"
    itf003: "https://192.168.31.81:8443/services/api/v1/ITF003"
    accessKey: "INFOPLUS"
    signature: "iwIY9hx1ckg="
    
server:
  port : 8082

template:
     path: "/usr/local/InfoCMS/was/templates/"  

upload:
  path: "/home/was/info_cms/consent/"
  url:
  user:
  password:
  port:
---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@121.166.140.188:1521:IWSPDB
    username: infoCMS
    password: koiware123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: LogHikariCP
      max-lifetime: 200000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

cravis:
  uri:
    ilogin: "https://192.168.31.81:8443/services/api/v1/ILOGIN"
    icfcti: "https://192.168.31.81:8443/services/api/v1/ICFCTI"
    ignotp: "https://192.168.31.81:8443/services/api/v1/IGNOTP"
    icfotp: "https://192.168.31.81:8443/services/api/v1/ICFOTP"
    isnsms: "https://192.168.31.81:8443/services/api/v1/ISNSMS"
    iec005: "https://192.168.31.81:8443/services/api/v1/IEC005"
    iac002: "https://192.168.31.81:8443/services/api/v1/IAC002"
    itf001: "https://192.168.31.81:8443/services/api/v1/ITF001"
    itf002: "https://192.168.31.81:8443/services/api/v1/ITF002"
    itf003: "https://192.168.31.81:8443/services/api/v1/ITF003"
    accessKey: "INFOPLUS"
    signature: "iwIY9hx1ckg="
    
server:
  port : 8082
    
template:
     path: "/usr/local/InfoCMS/was/templates/"  

upload:
  path: "/home/was/info_cms/consent/"
  url:
  user:
  password:
  port:
---

spring:
  config:
    activate:
      on-profile: "common"
#  boot:
#    admin:
#      client:
#        url:
#        - http://localhost:58082
      
  jackson:
    serialization:
      indent-output: true
    deserialization:      
      fail-on-unknown-properties: true
      
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
  messages:
    basename: i18n/exception
    encoding: UTF-8
  
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    
management:
  endpoints:
    web:
      exposure: ## Http상에서 endpoint 공개하는 방법
        include: 'env,metrics,health'
      base-path: '/'
#    enabled-by-default: false
  endpoint:
    shutdown:
      enabled: false
#    info: ## endpoint 활성화 및 비활성화 방법
#      enabled: true
    health:
      show-details: always
      
---

spring:
  profiles:
    group:
      "local": "local,common"
      "dev":  "dev,common"
      "prod": "prod,common"



      
      
      