

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@121.166.140.188:1521:IWSPDB
    username: infoCMS
    password: koiware123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: LogHikariCP
      max-lifetime: 200000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

           
mybatis:
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    
server:
  port : 8082
     

  
      




    

      
      